IF OBJECT_ID(N'Attestates', N'U') IS NULL
BEGIN

CREATE TABLE Attestates
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(32) NOT NULL, 
	[Date] DATETIME NOT NULL,
	[ValidDate] DATETIME NOT NULL
)

END

IF OBJECT_ID(N'Certificates', N'U') IS NULL
BEGIN

CREATE TABLE Certificates
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Number] NVARCHAR(32) NOT NULL,
    [Date] DATETIME NOT NULL,
	[ValidDate] DATETIME NULL
)

END

IF OBJECT_ID(N'Contracts', N'U') IS NULL
BEGIN

CREATE TABLE Contracts
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(20) NOT NULL,
    [ShortName] NVARCHAR(20) NOT NULL,
    [Number] NVARCHAR(32) NOT NULL,
	[Date] DATETIME NOT NULL
)

END

IF OBJECT_ID(N'Declarations', N'U') IS NULL
BEGIN

CREATE TABLE Declarations
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(32) NOT NULL,
	[Date] DATETIME NOT NULL,
	[ValidDate] DATETIME NULL
)

END

IF OBJECT_ID(N'GovStandards', N'U') IS NULL
BEGIN

CREATE TABLE GovStandards
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(20) NOT NULL, 
	[Name] NVARCHAR(128) NOT NULL,
	[Paragraphs] NVARCHAR(128) NULL
)

END

IF OBJECT_ID(N'GTDs', N'U') IS NULL
BEGIN

CREATE TABLE GTDs
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(32) NOT NULL, 
	[Date] DATETIME NULL,
)

END

IF OBJECT_ID(N'Invoices', N'U') IS NULL
BEGIN

CREATE TABLE Invoices
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(32) NOT NULL, 
	[ShortName] NVARCHAR(32) NOT NULL,
	[Number] NVARCHAR(32) NOT NULL,
	[Date] DATETIME NULL
)

END

IF OBJECT_ID(N'ManufacturerStandards', N'U') IS NULL
BEGIN

CREATE TABLE ManufacturerStandards
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(32) NOT NULL, 
	[Name] NVARCHAR(128) NOT NULL,
	[Date] DATETIME NULL
)

END

IF OBJECT_ID(N'TechRegs', N'U') IS NULL
BEGIN

CREATE TABLE TechRegs
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(16) NOT NULL, 
	[Name] NVARCHAR(256) NOT NULL,
	[ShortName] NVARCHAR(256) NOT NULL,
	[ApprovedByInfo] NVARCHAR(128) NOT NULL,
	[Paragraphs] NVARCHAR(128) NULL
)

END

IF OBJECT_ID(N'TestProtocols', N'U') IS NULL
BEGIN

CREATE TABLE TestProtocols
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Number] NVARCHAR(32) NOT NULL, 
	[Date] DATETIME NOT NULL,
	[LaboratoryId] INT NOT NULL
)

END