IF OBJECT_ID(N'Addresses', N'U') IS NULL
BEGIN

CREATE TABLE Addresses
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Country] NVARCHAR(128) NULL, 
	[Index] NVARCHAR(16) NULL,
	[AddressLine] NVARCHAR(256) NULL
)

END

IF OBJECT_ID(N'BankAccounts', N'U') IS NULL
BEGIN

CREATE TABLE BankAccounts
(
	[Id] INT NOT NULL PRIMARY KEY,
	[IIK] NVARCHAR(20) NULL, 
	[BIK] NVARCHAR(8) NULL,
	[BankName] NVARCHAR(128) NULL
)

END